Parameters:
  App:
    Type: String
  Env:
    Type: String
  Name:
    Type: String
  AWSAccountID:
    Type: String

Resources:
  SNSAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Resource: '*'
          Effect: Allow
          Action: sns:Publish

  LambdaAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Resource: '*'
          Effect: Allow
          Action:
            - lambda:InvokeFunction
            - lambda:InvokeAsync

  StepFunctionsAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Resource: '*'
          Effect: Allow
          Action: states:StartExecution

  S3AccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Resource: '*'
          Effect: Allow
          Action: s3:*

  WebsocketsAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Resource: '*'
          Effect: Allow
          Action: execute-api:*

Outputs:
  SNSAccessPolicy:
    Value: !Ref SNSAccessPolicy

  LambdaAccessPolicy:
    Value: !Ref LambdaAccessPolicy

  StepFunctionsAccessPolicy:
    Value: !Ref StepFunctionsAccessPolicy

  S3AccessPolicy:
    Value: !Ref S3AccessPolicy

  WebsocketsAccessPolicy:
    Value: !Ref WebsocketsAccessPolicy
