export const fallbackFlags = {
  spaces: true,
  orders: true,
  launchkit: true,
  outstandingOrders: true,
  payments: true,
  hmPay: true,
  stripeConnect: true,
  whatsNew: true,
  messages: true,
  bookings: true,
  pointsOfInterest: true,
  marketplace: true,
  support: true,
  products: true,
};
